# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: nirban-first-vgrp

parameters:
  - name: SubscriptionName
    displayName: "Enter Subscription Name"
    type: string
    default: MCT
    
  - name: WebAppName
    displayName: 'Enter WebAppName'
    type: string
    default: webapp

  - name: ResourceGroupName
    displayName: "Enter ResourceGroupName"
    type: string
    default: rg-new

  - name: UserAccount
    displayName: "Enter UserAccount for Access like:- test@xyx.com"
    type: string
    default: nirban

  - name: AccessType
    displayName: "Enter Access Type"
    type: string
    default: Contributor
    values:
        - Reader
        - Contributor
        - Owner

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo this is my name
    echo $(name)
    echo $(parameters.SubscriptionName)
  displayName: 'Run a multi-line script'
